import { ToastContainer } from 'react-toastify';
import ReactQueryProvider from '@/provider/react-query-context';

import 'react-toastify/dist/ReactToastify.min.css';
import '../../public/css/bootstrap.min.css';
import '../../public/css/font.css';
import '../../public/css/global.css';
import '../../public/css/components.css';
import '../../public/css/admin.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <div className="__next">{children}</div>
          <ToastContainer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
